blank_issues_enabled: true

contact_links:
  - name: Official MkLume documentation
    url: https://www.ecalstudios.com/mklume/
    about: Read the official MkLume documentation.

  - name: Support development on Ko-fi
    url: https://ko-fi.com/ecalstudios
    about: Optional donation link for supporting MkLume development. Not for technical support.
