import {
  Camera,
  ClipboardCheck,
  Timer,
  Languages,
  BookOpen,
  Rocket,
  Settings,
  CircleAlert,
  CircleCheck,
  Info,
  Lightbulb,
  Package,
  FileText,
  Folder,
  ImageIcon,
  Braces,
  ArrowRight,
  GitBranch,
  Download,
  Upload,
  Link,
  Star,
  Heart,
  Eye,
  Pencil,
  Trash2,
  Plus,
  Minus,
  X,
  Search,
  Home,
  User,
  Lock,
  ShieldCheck,
  Bug,
  Wrench,
  TestTube2,
  BarChart3,
  Mail,
  Bell,
  Calendar,
  Clock,
  MapPin,
  Cloud,
  Database,
  Server,
  Play,
  Square,
  Globe,
  Bookmark,
  MessageSquare,
  type LucideIcon,
} from "lucide-react";

export interface IconPreset {
  shortcode: string;
  label: string;
  icon: LucideIcon;
}

const ICON_MAP: Record<string, LucideIcon> = {
  "camera": Camera,
  "clipboard-check": ClipboardCheck,
  "timer": Timer,
  "timer-outline": Timer,
  "translate": Languages,
  "book-open-page-variant": BookOpen,
  "book-open": BookOpen,
  "book": BookOpen,
  "rocket-launch": Rocket,
  "rocket": Rocket,
  "cog": Settings,
  "settings": Settings,
  "alert-circle": CircleAlert,
  "alert": CircleAlert,
  "check-circle": CircleCheck,
  "check": CircleCheck,
  "information": Info,
  "info": Info,
  "lightbulb": Lightbulb,
  "lightbulb-outline": Lightbulb,
  "package-variant": Package,
  "package": Package,
  "language-markdown": Braces,
  "file-document": FileText,
  "file-document-outline": FileText,
  "file": FileText,
  "folder": Folder,
  "folder-open": Folder,
  "image": ImageIcon,
  "code-braces": Braces,
  "code": Braces,
  "download": Download,
  "upload": Upload,
  "link": Link,
  "link-variant": Link,
  "star": Star,
  "star-outline": Star,
  "heart": Heart,
  "heart-outline": Heart,
  "eye": Eye,
  "eye-outline": Eye,
  "pencil": Pencil,
  "pencil-outline": Pencil,
  "delete": Trash2,
  "delete-outline": Trash2,
  "plus": Plus,
  "plus-circle": Plus,
  "minus": Minus,
  "minus-circle": Minus,
  "close": X,
  "close-circle": X,
  "magnify": Search,
  "search": Search,
  "home": Home,
  "home-outline": Home,
  "account": User,
  "account-circle": User,
  "lock": Lock,
  "lock-outline": Lock,
  "shield-check": ShieldCheck,
  "shield": ShieldCheck,
  "bug": Bug,
  "bug-outline": Bug,
  "wrench": Wrench,
  "wrench-outline": Wrench,
  "test-tube": TestTube2,
  "chart-bar": BarChart3,
  "chart-line": BarChart3,
  "email": Mail,
  "email-outline": Mail,
  "bell": Bell,
  "bell-outline": Bell,
  "calendar": Calendar,
  "calendar-outline": Calendar,
  "clock": Clock,
  "clock-outline": Clock,
  "map-marker": MapPin,
  "map-marker-outline": MapPin,
  "cloud": Cloud,
  "cloud-outline": Cloud,
  "database": Database,
  "database-outline": Database,
  "server": Server,
  "play": Play,
  "play-circle": Play,
  "stop": Square,
  "stop-circle": Square,
  "web": Globe,
  "earth": Globe,
  "bookmark": Bookmark,
  "bookmark-outline": Bookmark,
  "message": MessageSquare,
  "comment": MessageSquare,
  "github": GitBranch,
  "gitbook": BookOpen,
  "arrow-right": ArrowRight,
  "arrow-right-24": ArrowRight,
};

export function resolveIcon(shortcode: string): LucideIcon | null {
  const inner = shortcode.replace(/^:/, "").replace(/:$/, "");
  // Strip family prefix: material-, fontawesome-solid-, fontawesome-brands-, simple-, octicons-
  const name = inner
    .replace(/^material-/, "")
    .replace(/^fontawesome-solid-/, "")
    .replace(/^fontawesome-brands-/, "")
    .replace(/^fontawesome-regular-/, "")
    .replace(/^simple-/, "")
    .replace(/^octicons-/, "")
    .replace(/^emoji-/, "");

  return ICON_MAP[name] ?? null;
}

export const ICON_PRESETS: IconPreset[] = [
  { shortcode: ":material-book-open-page-variant:", label: "Book", icon: BookOpen },
  { shortcode: ":material-rocket-launch:", label: "Rocket", icon: Rocket },
  { shortcode: ":material-cog:", label: "Settings", icon: Settings },
  { shortcode: ":material-alert-circle:", label: "Alert", icon: CircleAlert },
  { shortcode: ":material-check-circle:", label: "Check", icon: CircleCheck },
  { shortcode: ":material-information:", label: "Info", icon: Info },
  { shortcode: ":material-lightbulb:", label: "Idea", icon: Lightbulb },
  { shortcode: ":material-package-variant:", label: "Package", icon: Package },
  { shortcode: ":material-language-markdown:", label: "Markdown", icon: Braces },
  { shortcode: ":material-file-document:", label: "Document", icon: FileText },
  { shortcode: ":material-folder:", label: "Folder", icon: Folder },
  { shortcode: ":material-image:", label: "Image", icon: ImageIcon },
  { shortcode: ":material-code-braces:", label: "Code", icon: Braces },
  { shortcode: ":material-camera:", label: "Camera", icon: Camera },
  { shortcode: ":material-clipboard-check:", label: "Clipboard", icon: ClipboardCheck },
  { shortcode: ":material-timer-outline:", label: "Timer", icon: Timer },
  { shortcode: ":material-translate:", label: "Translate", icon: Languages },
  { shortcode: ":material-download:", label: "Download", icon: Download },
  { shortcode: ":material-upload:", label: "Upload", icon: Upload },
  { shortcode: ":material-link:", label: "Link", icon: Link },
  { shortcode: ":material-star:", label: "Star", icon: Star },
  { shortcode: ":material-heart:", label: "Heart", icon: Heart },
  { shortcode: ":material-eye:", label: "View", icon: Eye },
  { shortcode: ":material-pencil:", label: "Edit", icon: Pencil },
  { shortcode: ":material-delete:", label: "Delete", icon: Trash2 },
  { shortcode: ":material-plus:", label: "Add", icon: Plus },
  { shortcode: ":material-minus:", label: "Remove", icon: Minus },
  { shortcode: ":material-close:", label: "Close", icon: X },
  { shortcode: ":material-magnify:", label: "Search", icon: Search },
  { shortcode: ":material-home:", label: "Home", icon: Home },
  { shortcode: ":material-account:", label: "User", icon: User },
  { shortcode: ":material-lock:", label: "Lock", icon: Lock },
  { shortcode: ":material-shield-check:", label: "Security", icon: ShieldCheck },
  { shortcode: ":material-bug:", label: "Bug", icon: Bug },
  { shortcode: ":material-wrench:", label: "Tools", icon: Wrench },
  { shortcode: ":material-test-tube:", label: "Test", icon: TestTube2 },
  { shortcode: ":material-chart-bar:", label: "Chart", icon: BarChart3 },
  { shortcode: ":material-email:", label: "Email", icon: Mail },
  { shortcode: ":material-bell:", label: "Notification", icon: Bell },
  { shortcode: ":material-calendar:", label: "Calendar", icon: Calendar },
  { shortcode: ":material-clock:", label: "Time", icon: Clock },
  { shortcode: ":material-map-marker:", label: "Location", icon: MapPin },
  { shortcode: ":material-cloud:", label: "Cloud", icon: Cloud },
  { shortcode: ":material-database:", label: "Database", icon: Database },
  { shortcode: ":material-server:", label: "Server", icon: Server },
  { shortcode: ":material-play:", label: "Play", icon: Play },
  { shortcode: ":fontawesome-brands-github:", label: "GitHub", icon: GitBranch },
  { shortcode: ":fontawesome-solid-download:", label: "Download", icon: Download },
  { shortcode: ":octicons-arrow-right-24:", label: "Arrow Right", icon: ArrowRight },
  { shortcode: ":simple-github:", label: "GitHub", icon: GitBranch },
  { shortcode: ":simple-gitbook:", label: "GitBook", icon: BookOpen },
];

export const ICON_SHORTCODE_REGEX =
  /:(material|fontawesome|simple|octicons|emoji)-[a-zA-Z0-9-]+:/g;

export function isIconShortcode(text: string): boolean {
  return /^:(material|fontawesome|simple|octicons|emoji)-[a-zA-Z0-9-]+:$/.test(text);
}
